### ISSUE TITLE
c.add_comment(b"") breaks image

### ISSUE THREAD

**Issue by niklasf** [DougLau/gift#18]
Because the encoding will contain one `0` for the empty string (but it already ends the block), followed by another `0` to end the block. Perhaps there should be a non-empty assertion similar to the max length, or maybe empty comments should be skipped.

**Comment by DougLau** [comment]
It makes sense to add a non-empty assert.
This also affects PlainText.add_sub_block, Application.add_app_data and Unknown.add_sub_block.
