### ISSUE TITLE
[wip] Four issues I've run into while using`gift`.

### ISSUE THREAD

**Issue by follower** [DougLau/gift#20]
Thanks for your work on this crate.

I'm creating this issue with a brief overview of some issues I've run into during use. (Which would be better to be created as individual issues but currently the most likely alternative is not to write them up at all, so hopefully this format is better than nothing. :) )

- [x] 1. Add note to docs/README to items that are still `todo!` e.g. full color to indexed & the binary sub commands.
- [x] 2. Add tag/release for 0.9.1 which is [listed on `crates.io`](https://crates.io/crates/gift/0.9.1) but not tagged in repo.
- [x] 3. Both v0.9.1 and [current `master`](https://github.com/DougLau/gift/tree/102f3b5e62b32455ad7408cea8ecc2abf1dfe644) handle `min_code_bits` incorrectly for the values `4` & `8` when encoding. (see below) 
- [x] 4. [current `master`](https://github.com/DougLau/gift/tree/102f3b5e62b32455ad7408cea8ecc2abf1dfe644) does not encode images of dimensions such as 2x2 or 3x3 successfully. (8x8 appears to work.) I haven't investigated why but my guess is it's related to the new `lzw` implementation.
- [x] 5. More validity/regression tests would be helpful.

### 3. More on `min_code_bits` 

For the value `4` `min_code_size` is set to `2` instead of `3` this results in the colour index being encoded as `0` and the incorrect colour appearing.

This occurs here: https://github.com/DougLau/gift/blob/102f3b5e62b32455ad7408cea8ecc2abf1dfe644/src/encode.rs#L212-L213

[TODO: Provide more details, examples & code.]

 * See also:

    * https://github.com/image-rs/image-gif/blob/master/src/encoder.rs#L287

    * http://www.matthewflickinger.com/lab/whatsinagif/lzw_image_data.asp#lzw_compression (min code size vs color code table)

#### Patch/workaround

This patch/workaround "fixed" the issue for me but strictly speaking probably isn't entirely specification compliant[1]:

```diff
diff --git a/src/encode.rs b/src/encode.rs
index be410e7..8de1a9a 100644
--- a/src/encode.rs
+++ b/src/encode.rs
@@ -210,7 +210,7 @@ impl ImageData {
     /// Format an image data block
     fn format<W: Write>(&self, w: &mut W) -> io::Result<()> {
         let min_code_bits =
-            next_high_bit(self.data().iter().copied().max().unwrap_or(0));
+            next_high_bit(self.data().iter().copied().max().unwrap_or(0)+1);
         // minimum code bits must be between 2 and 12
         let min_code_bits = 2.max(min_code_bits).min(12);
         w.write_all(&[min_code_bits])?;
```

[1] Because AFAICT the value is intended to be related to the bit-depth.

Example _animated GIF_ exported with workaround in place:

<details>

![output16](https://user-images.githubusercontent.com/189962/96513781-28f30200-12bf-11eb-9cc4-74dd246f1e37.gif)

</details>

#### Related tools

 * http://www.matthewflickinger.com/lab/whatsinagif/gif_explorer.asp -- I *highly* recommend this "GIF Explorer" tool for viewing *valid* GIF files that are incorrectly encoded in some way. (It's what I used to identify that the colour index `4` was being encoded as `0`.)

*Edited:* Added additional content.

**Comment by DougLau** [comment]
From looking at the first link, it appears the fix should instead be:
```diff
diff --git a/src/encode.rs b/src/encode.rs
index be410e7..22a391a 100644
--- a/src/encode.rs
+++ b/src/encode.rs
@@ -210,7 +210,7 @@ impl ImageData {
     /// Format an image data block
     fn format<W: Write>(&self, w: &mut W) -> io::Result<()> {
         let min_code_bits =
-            next_high_bit(self.data().iter().copied().max().unwrap_or(0));
+            next_high_bit(self.data().iter().copied().max().unwrap_or(0)) + 1;
         // minimum code bits must be between 2 and 12
         let min_code_bits = 2.max(min_code_bits).min(12);
         w.write_all(&[min_code_bits])?;
```

Do you have sample images for regression testing?  If not, I can come up with something.

**Comment by DougLau** [comment]
All mentioned problems were related to min_code_bits calculation.
